/*
on the name of god
author: Parag Jain
problem 2: 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
Date: 3/3/2020
*/
#include <iostream>

using namespace std;

int main()
{
    int n=4000000; //input
    int first_no=1;
    int second_no=2;
    int temp_sum,sum_even=2;
    while(second_no<n)
    {   temp_sum=0;
        temp_sum=first_no+second_no;
        if(temp_sum%2==0)
        {
            sum_even=sum_even+temp_sum;
        }
        first_no=second_no;
        second_no=temp_sum;
    } 
    cout<<sum_even; //output
    return 0;
}